CREATE TABLE clubs (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    city VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stadiums (
    id BIGSERIAL PRIMARY KEY,
    club_id BIGINT REFERENCES clubs(id) ON DELETE SET NULL,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sections (
    id BIGSERIAL PRIMARY KEY,
    stadium_id BIGINT NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT 'STANDARD',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_stadium_section UNIQUE (stadium_id, name)
);

CREATE TABLE rows (
    id BIGSERIAL PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    row_number VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_section_row UNIQUE (section_id, row_number)
);

CREATE TABLE seats (
    id BIGSERIAL PRIMARY KEY,
    row_id BIGINT NOT NULL REFERENCES rows(id) ON DELETE CASCADE,
    seat_number VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_row_seat UNIQUE (row_id, seat_number)
);

CREATE TABLE matches (
    id BIGSERIAL PRIMARY KEY,
    home_club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    away_club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    stadium_id BIGINT NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE,
    kickoff_time TIMESTAMP WITH TIME ZONE NOT NULL,
    season VARCHAR(20) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_matches_season_home ON matches(season, home_club_id);
CREATE INDEX idx_matches_kickoff ON matches(kickoff_time);
